#!/bin/sh
# --- SDE-COPYRIGHT-NOTE-BEGIN ---
# This copyright note is auto-generated by ./scripts/Create-CopyPatch.
#
# Filename: target/mnemosyne/overlay.d/pkgs/clockspeed/D%sysconfdir_clockspeed_clockspeed_run.sh
# Copyright (C) 2008 - 2010 The OpenSDE Project
#
# More information can be found in the files COPYING and README.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License. A copy of the
# GNU General Public License can be found in the file COPYING.
# --- SDE-COPYRIGHT-NOTE-END ---

exec 2>&1

if [ ! -e /var/state/clockspeed/adjust ]; then
	D_bindir/clockctl sync || exit 1
fi

echo "Starting clockspeed"
exec D_bindir/clockspeed
